// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqc8jL2CiV2NcE6WonZRrUpBkjV86KDtI',
    appId: '1:689693805665:web:2c34c3907a80ff7096ae20',
    messagingSenderId: '689693805665',
    projectId: 'x-wash-d8e11',
    authDomain: 'x-wash-d8e11.firebaseapp.com',
    storageBucket: 'x-wash-d8e11.appspot.com',
    measurementId: 'G-DM9RX3DVGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnw0IEP6BMExXnc7LsRp2lw97jU6ELy0s',
    appId: '1:689693805665:android:3225dc05ec7d39e196ae20',
    messagingSenderId: '689693805665',
    projectId: 'x-wash-d8e11',
    storageBucket: 'x-wash-d8e11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-ax56f4O7JFOkd5CqzkHOwZQzyDemdhM',
    appId: '1:689693805665:ios:b76f55844a6c3fb196ae20',
    messagingSenderId: '689693805665',
    projectId: 'x-wash-d8e11',
    storageBucket: 'x-wash-d8e11.appspot.com',
    iosClientId: '689693805665-n3q12jbrdd055s0l9qsvq2mlipo81q5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.xwash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-ax56f4O7JFOkd5CqzkHOwZQzyDemdhM',
    appId: '1:689693805665:ios:b76f55844a6c3fb196ae20',
    messagingSenderId: '689693805665',
    projectId: 'x-wash-d8e11',
    storageBucket: 'x-wash-d8e11.appspot.com',
    iosClientId: '689693805665-n3q12jbrdd055s0l9qsvq2mlipo81q5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.xwash',
  );
}
